server:
  port: 9000

spring:
  security:
    oauth2:
      client:
        registration:
          github-idp:
            provider: github
            client-id: 2205af0f0cc93e3a22ea
            client-secret: 649d88df840a57d2591c4832b438cc9af2727240
#            redirect-uri: http://192.168.56.1:9000/login/oauth2/code/github-idp # 这个地方可以不配置，配置就要与github的应用配置回调一致
            scope: user:email, read:user
            client-name: Sign in with GitHub
          gitee:
            # 指定oauth登录提供者，该oauth登录由provider中的gitee来处理
            provider: gitee
            # 客户端名字
            client-name: Sign in with Gitee
            # 认证方式
            authorization-grant-type: authorization_code
            # 客户端id，使用自己的gitee的客户端id
            client-id: 54f931645f6939f65fd8a24d2b9e659d8e164c655f6fd17c80e3f622a6a762e3
            # 客户端秘钥，使用自己的gitee的客户端秘钥
            client-secret: 38a797510aa8188cbc69242eaeb4f91d74ee6ad2cabeb88e2418c2cef40675d0
            # 回调地址 与gitee 配置的回调地址一致才行
            redirect-uri: http://demo.server.com:9000/login/oauth2/code/gitee
            #http://192.168.56.1:9000/login/oauth2/code/gitee
            # 申请scope列表
            scope:
              - emails
              - user_info
        provider:
          github:
            user-name-attribute: login
          gitee:
            # 设置用户信息名称对应的字段属性
            user-name-attribute: login
            # 获取token的地址
            token-uri: https://gitee.com/oauth/token
            # 获取用户信息的地址
            user-info-uri: https://gitee.com/api/v5/user
            # 发起授权申请的地址
            authorization-uri: https://gitee.com/oauth/authorize

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org.springframework.security.oauth2.client: trace